CI Test Improvement
KenSciResearch/fairMLHealth pull request #24
Opened 2020-12-04 01:09 UTC by camagallen

Updated methodology for more robust testing.

2020-12-11 09:29 UTC, kenviku requested changes

2020-12-11 09:29 UTC, kenviku commented on fairmlhealth/model_comparison.py
> +        if self.models is not None:
based on the above checks, I do not see a scenario where this code will be executed!

2020-12-11 09:29 UTC, kenviku commented on fairmlhealth/reports.py
> +    __validate_report_inputs(X, prtc_attr, y_true, y_pred, y_prob, priv_grp)
Aren't the reports code-generated (instead of user-generated)? Do you need a validation function in that case?

2020-12-11 09:29 UTC, kenviku commented on test/test_validations.py
> +if __name__ == '__main__':
Use `unittest.main()`. Strongly recommended: Use `pytest` - helps simplify a lot of boilerplate code.

2020-12-11 09:29 UTC, kenviku commented on test/test_validations.py
> +        assert not any(t is None for t in [test1, test2, test3, test4])
Separate unique functional testing into its own test case! (Recommendation: Use `pytest`)

2020-12-11 09:29 UTC, kenviku commented on test/test_validations.py
> +        with self.assertRaises(ValidationError):
Same as above. Separate functional/scenarios of each test into own independent test case!

2020-12-11 09:32 UTC, kenviku commented on test/test_validations.py
> +Validation tests forfairMLHealth
```suggestion
Validation tests for fairmlhealth
```

2020-12-11 15:13 UTC, camagallen commented on fairmlhealth/model_comparison.py
>          self.y = target_data
X is a set of features and y is a single series

2020-12-11 15:16 UTC, camagallen commented on fairmlhealth/model_comparison.py
> +            msg = f"Could not measure fairness for {model_name}. Name" + \
The issue with multiline strings is that it will include newlines and spaces, so I would have to do postprocessing to make the message look right. However, I have been considering declaring the string within parentheses since it's cleaner.

2020-12-11 15:16 UTC, camagallen commented on fairmlhealth/model_comparison.py
> +            msg = f"Failure generating predictions for {model_name} model." + \
See previous comment.

2020-12-11 15:58 UTC, camagallen commented on fairmlhealth/model_comparison.py
> +        if self.models is not None:
Oh, good catch!

2020-12-11 16:04 UTC, camagallen commented on fairmlhealth/reports.py
> +    __validate_report_inputs(X, prtc_attr, y_true, y_pred, y_prob, priv_grp)
The main report functions are not hidden, and therefore available to the user. I haven't written documentation to bring them to the user's attention, but I would like to leave open the possibility that people can generate reports without going through model_comparison.

2020-12-11 18:33 UTC, camagallen commented on test/test_validations.py
> +if __name__ == '__main__':
resolved

2020-12-14 08:05 UTC, kenviku reviewed
LGTM. Awaiting approval once build passes.

2020-12-15 00:11 UTC, kenviku approved these changes

2020-12-17 19:28 UTC, merged