Test updates
KenSciResearch/fairMLHealth pull request #30
Opened 2021-04-15 00:41 UTC by camagallen

# Pull Request Submission

## About
Adding integrated/automated testing for the most important example/tutorial notebooks, plus improving contribution guidelines and documentation. 

Resolves: AB#14708

## Integration Issues
None, although integrated testing will be prolonged due to the models in the notebooks

## Checklist
- [X] I have read the [Contributing](CONTRIBUTING.md) guidelines.
- [X] I performed a self-review of my own code.
- [X] The CHANGELOG and version.json have been updated.
- [ X] Documentation has been updated to reflect the changes.
    - [X] The code has clear and helpful comments, particularly in hard-to-understand areas.
    - [X] READMEs, Tutorials/Examples, and links have been updated as appropriate.
        - Note: some READMEs have links that will be updated in a near-future PR, to be included for the next version
- [ X] Tests have been added to prove that the fix is effective or that the feature works.
- [ X] Pytest was run; new and existing unit tests pass locally with my changes.
- [ X] I have made note of any breakages or dependencies (if applicable).
- [ X] Any dependent changes have been merged and published in downstream modules.
- [ X] These changes generate no new warnings.

## How was this update tested?
pytest

2021-04-15 22:51 UTC, kenviku requested changes
I will wait for you to fix #30 merge to align with #29 for any further review/comments. Let me know if any questions.

By the way, thanks for adding the necessary documents around Code of conduct and Contributions!

2021-04-15 22:51 UTC, kenviku commented on CHANGELOG.md
> +### Flexibility Update
@camagallen - If you recreate this PR to commit from your branch of `test_updates` to `q1_code_update` then it will only show the incremental changes to your current PR. Currently, I see the similar changes to be reviewed in PR #29 too.

2021-04-15 22:51 UTC, kenviku commented on docs/development/CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
Thanks for including this. Any reason for this specific code of conduct guideline?

2021-04-15 22:51 UTC, kenviku commented on docs/development/CONTRIBUTING.md
> +If you'd like help troubleshooting a docs PR you're working on, have a great new idea, or want to share something amazing you've learned in our docs, join us in [discussions](https://github.com/githu
shouldn't the discussion link here be referred to our `discussion` page?

2021-04-15 22:51 UTC, kenviku commented on docs/development/CONTRIBUTING.md
> +- Check out the [existing issues](https://github.com/github/docs/issues) & see if we [accept contributions](#types-of-contributions-memo) for your type of issue.
link of existing issues to current repo issues!?

2021-04-15 22:51 UTC, kenviku commented on docs/development/CONTRIBUTING.md
> +Once your PR is merged, you will be proudly listed as a contributor in the [contributor chart](https://github.com/github/docs/graphs/contributors).
Link correction!

2021-04-15 22:51 UTC, kenviku commented on docs/development/CONTRIBUTING.md
> +[Issues](https://docs.github.com/en/github/managing-your-work-on-github/about-issues) are used to track tasks that contributors can help with. If an issue has a triage label, we haven't reviewed it y
Check all the links here and below to make this specific for the repo!

2021-04-16 00:24 UTC, camagallen commented on docs/development/CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
Not really. Is there a better one I should reference?

2021-04-16 01:57 UTC, kenviku approved these changes

2021-04-16 01:57 UTC, kenviku commented on docs/development/CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
I dont know! This one looks solid!

2021-04-16 01:57 UTC, kenviku commented on test/test_tutorial_evaluatingbinaryclassification.py
> +'''
The notebook tests are great! Thanks to include these as part of the this repo!

Do you think its better to include the notebook tests in a folder of its own? like `test\notebooks\`

2021-04-21 03:28 UTC, merged