Flag update
KenSciResearch/fairMLHealth pull request #46
Opened 2021-06-23 20:46 UTC by camagallen

## Overview
- Adds flagging functionality for stratified reports (bias_report, performance_report, data_report)
- Updates flagging function s.t. it can be called as an argument in the model_comparison or bias_report functions

Resolves: ...

## Checklist
- [X] I have read the [Contributing](https://github.com/KenSciResearch/docs/code_contributions/CONTRIBUTING.md) guidelines
- [X] I performed a self-review of my own code
- [] The CHANGELOG and version.json have been updated
- [] Documentation has been updated to reflect the changes
    - [] The code has clear and helpful comments, particularly in hard-to-understand areas
    - [] READMEs, Tutorials/Examples, and links have been updated as appropriate
- [X] Tests have been added to prove that the fix is effective or that the feature works
- [X] Pytest was run; new and existing unit tests pass locally with my changes
- [X] I have made note of any breakages or dependencies (if applicable)
- [X] Any dependent changes have been merged and published in downstream modules
- [X] These changes generate no new warnings

## How was this update tested?
pytest and visual inspection of notebooks

2021-06-23 21:23 UTC, camagallen reviewed
LGTM

2021-06-23 21:23 UTC, camagallen commented on setup.py
> +
Moved the function definition to the top of the script here.

2021-06-23 21:23 UTC, camagallen commented on test/test_modelcomparison.py
Turned off flagging for test_modelcomparison since flagging is tested in the jupyter notebooks

2021-06-24 20:52 UTC, kenviku requested changes

2021-06-24 20:52 UTC, kenviku commented on fairmlhealth/model_comparison.py
> +                   predictions=None, probabilities=None, flag_oor=False):
Default value for `flag_oor` shall be True! This will ensure that users are then able to make choice of not using the flag.

2021-06-24 20:52 UTC, kenviku commented on fairmlhealth/model_comparison.py
> +    def compare_measures(self, flag_oor=False):
same here

2021-06-24 20:52 UTC, kenviku commented on fairmlhealth/reports.py
> +def summary_report(X, prtc_attr, y_true, y_pred, y_prob=None, flag_oor=False,
same

2021-06-25 20:13 UTC, kenviku requested changes

2021-06-25 20:13 UTC, kenviku commented on fairmlhealth/model_comparison.py
> +                  predictions=None, probabilities=None, flag_oor=True):
👍

2021-06-25 20:13 UTC, kenviku commented on fairmlhealth/model_comparison.py
> +    def compare_measures(self, flag_oor=False):
`flag_oor=True`?

2021-06-25 23:39 UTC, kenviku approved these changes
LGTM

2021-06-26 00:06 UTC, merged