Tutorial Cleanup and Ad
KenSciResearch/fairMLHealth pull request #5
Opened 2020-10-08 04:58 UTC by camagallen

In this Update:

- updated README with organization and installation info

- minor restructuring to make the library more intuitive
        * new folders called "tools", "templates", and "tutorials_and_examples"
        * new naming schema imposed

- KDD 2020 tutorial is now "archived" in the publications folder with a redirect notice to see our - now intuitively named - "Tutorial-MeasuringFairnessInBinaryClassification.ipynb".
        * allows for consistent naming conventions
        * allows for continued improvement of the tutorial if needed (as needed) without compromising the original presentation

- cleaned code for the above notebooks

- updates to binary prediction model comparison template and example (with supplemental material)
        * cleaned code
        * added explanatory content to example and especially to supplemental material

2020-10-12 20:48 UTC, kenviku requested changes
Thanks for the PR. In future suggest to breakdown the PRs into multiple PRs focused on specific areas. Key comments apart from the respective inline comments:
1. Change the folder package name of `fairMLHealth` to `fairmlhealth`.
2. Remove the folders on `tutorials` and `templates` from the `fairmlhealth` and move them to be parent folders of the repo.
3. Copy the contents of `tools` folder into the `fairmlhealth` folder as parent. Remove the `tools` folder.
4. Add unit tests for the `FairCompare` class. (Use `pytest`)

Finally, for any of the change request that you wish to plan/address for later PRs, open an Azure Board work-item and assign a number to the respective comment.

2020-10-12 20:48 UTC, kenviku commented on fairMLHealth/tools/model_comparison.py
> +                raise ValueError(f"Error generating predictions for {model_name}" +
I think you are looking for existence of `predict` function. As a result, you may want to change the error to whether:
1. `predict()` function exists for the model.
2. can accept inputs of type numpy array of pandas. (this is covered under the `__validate()` function)

Similar to the type checking you have under `__validate()` you can also use that to validate the first clause

2020-10-12 20:48 UTC, kenviku commented on fairMLHealth/tools/model_comparison.py
> +        """ Generates a report comparing fairness measures for the model_name
A good doc string example includes both parameters definition and return statements. In the return statement, while including the type of return which is in this case a pandas dataframe shall also include what is returned. For a dataframe, the expected dimensions, what is in the rows , what are the columns.

2020-10-12 20:48 UTC, kenviku commented on fairMLHealth/tools/model_comparison.py
> +            print(f"Error measuring fairness: {model_name} does not appear in",
nit: For future work, convert `print` statements with python `logging`.

2020-10-12 20:48 UTC, kenviku commented on fairMLHealth/tools/reports.py
> +def regression_performance(y_true, y_pred):
👍

2020-10-12 20:48 UTC, kenviku commented on fairMLHealth/tools/reports.py
> +def classification_performance(y_true, y_pred, target_labels = None):
👍

2020-10-12 20:48 UTC, kenviku commented on fairMLHealth/tutorials_and_examples/Example-Template-BinaryClassificationAssessment.py
> +#!/usr/bin/env python
I believe this is a notebook converted to python file? Do you intend this to be used as notebook or a python file though? It has cell numbers and format that is only supported in notebooks.

2020-10-12 21:31 UTC, camagallen commented on fairMLHealth/tutorials_and_examples/Example-Template-BinaryClassificationAssessment.py
> +#!/usr/bin/env python
This line was added automatically by the converter.

2020-10-12 21:32 UTC, camagallen commented on fairMLHealth/tools/model_comparison.py
> +            print(f"Error measuring fairness: {model_name} does not appear in",
Oh, good point!

2020-10-12 21:41 UTC, camagallen commented on fairMLHealth/tools/format_mimic_data.py
> +            ].rename(columns = {'icd':'ICD9_CODE', 'ccs':f'{code_type}_CCS',
@kenviku I do have pylint  installed already, yes. It didn't flag this.

I also appear to have gotten overzealous about fixing some missing spaces. Have now switched to pylama and will fix these issues in the next PR.

2020-10-13 23:51 UTC, camagallen commented on README.md
> +
To be completed in AB#11661

2020-10-13 23:52 UTC, camagallen commented on fairMLHealth/templates/Template-BinaryClassificationAssessment.py
> +FairlearnDashboard(sensitive_features=protected_attr.to_list(),
To be completed in AB#11661

2020-10-13 23:54 UTC, camagallen commented on fairMLHealth/tools/model_comparison.py
> +            print(f"Error measuring fairness: {model_name} does not appear in",
To be added in AB#11662

2020-10-14 02:26 UTC, camagallen commented on fairMLHealth/tools/model_comparison.py
> +                raise ValueError(f"Error generating predictions for {model_name}" +
@kenviku the intention was to test whether the model has been fitted. Scikit has a "check_is_fitted" utility, but it appears to only work for scikit models. However we'd prefer for this object to accept any fitted model object with a predict() method... Will break this out as a separate testing function in AB#11665

2020-10-15 05:41 UTC, kenviku approved these changes
Thanks for the changes and capturing the pending changes in work-items. Can you please add one more work-item to track for code-coverage and build pipelines?

2020-10-15 05:41 UTC, kenviku commented on fairmlhealth/model_comparison.py
> +# Contributors: Christine Allen <christine.allen@kensci.com>
nit: You want to keep `camegellan`?

2020-10-16 20:29 UTC, camagallen commented on fairmlhealth/model_comparison.py
> +# Contributors: Christine Allen <christine.allen@kensci.com>
@kenviku I'm sorry, I don't understand what you're asking.

2020-10-19 16:12 UTC, merged